export const bodyPartNames = [
    'nose',
    'right eye inner',
    'right eye',
    'right eye outer',
    'left eye inner',
    'left eye',
    'left eye outer',
    'right ear',
    'left ear',
    'mouth right',
    'mouth left',
    'right shoulder',
    'left shoulder',
    'right elbow',
    'left elbow',
    'right wrist',
    'left wrist',
    'right pinky knuckle #1',
    'left pinky knuckle #1',
    'right index knuckle #1',
    'left index knuckle #1',
    'right thumb knuckle #2',
    'left thumb knuckle #2',
    'right hip',
    'left hip',
    'right knee',
    'left knee',
    'right ankle',
    'left ankle',
    'right heel',
    'left heel',
    'right foot index',
    'left foot index'
  ];
  